### ISSUE TITLE
Please include pom.xml in source code

### ISSUE THREAD

**Issue by PiggiesGoSqueal** [MisterMelDev/PetsPlus#3]
To my knowledge, it isn't possible for other people to build it via the source code without pom.xml?

-------------------
I'd need to do more research/learning I guess but I figured there is probably a way to list all entity types so you wouldn't need to manually type every one like you do here: (PetType.java)

	CHICKEN("Chicken", EntityType.CHICKEN, Sound.ENTITY_CHICKEN_AMBIENT, "MHF_Chicken", false),
	COW("Cow", EntityType.COW, Sound.ENTITY_COW_AMBIENT, "MHF_Cow", false),
	MUSHROOM("Mushroom", EntityType.MUSHROOM_COW, Sound.ENTITY_COW_AMBIENT, "MHF_MushroomCow", false),
	SHEEP("Sheep", EntityType.SHEEP, Sound.ENTITY_SHEEP_AMBIENT, "MHF_Sheep", false),
	RABBIT("Rabbit", EntityType.RABBIT, Sound.ENTITY_RABBIT_AMBIENT, "MHF_Rabbit", false),
	OCELOT("Ocelot", EntityType.OCELOT, Sound.ENTITY_OCELOT_AMBIENT, "MHF_Ocelot", false),
	PIG("Pig", EntityType.PIG, Sound.ENTITY_PIG_AMBIENT, "MHF_Pig", false),
	
	BABY_CHICKEN("Baby Chicken", EntityType.CHICKEN, Sound.ENTITY_CHICKEN_AMBIENT, "MHF_Chicken", true),
	BABY_COW("Baby Cow", EntityType.COW, Sound.ENTITY_COW_AMBIENT, "MHF_Cow", true),
	BABY_MUSHROOM("Baby Mushroom", EntityType.MUSHROOM_COW, Sound.ENTITY_COW_AMBIENT, "MHF_MushroomCow", true),
	BABY_SHEEP("Baby Sheep", EntityType.SHEEP, Sound.ENTITY_SHEEP_AMBIENT, "MHF_Sheep", true),
	BABY_RABBIT("Baby Rabbit", EntityType.RABBIT, Sound.ENTITY_RABBIT_AMBIENT, "MHF_Rabbit", true),
	BABY_OCELOT("Baby Ocelot", EntityType.OCELOT, Sound.ENTITY_OCELOT_AMBIENT, "MHF_Ocelot", true),
	BABY_PIG("Baby Pig", EntityType.PIG, Sound.ENTITY_PIG_AMBIENT, "MHF_Pig", true);

But I'm fairly new to Java/Plugin development so I could be wrong.

**Comment by melluh** [comment]
This project doesn't have a pom.xml, since it doesn't use Maven. The easiest way to build it would probably be to import the files into Eclipse (or some other IDE) and export it as a JAR file (In Eclipse this is Export -> JAR file).

As for the PetType enum, I think this may be the simplest way to do it. If you wanted to use EntityType directly, you would need a way to convert the EntityType into the Sound and the name of the skull owner. Sound is not entirely consistent (for example, `mushroom` uses `ENTITY_COW_AMBIENT`). If you did convert from EntityType directly, you could of course add in an exception for this. But at that point I think it would just be more readable to use an separate enum like I am now.

I'm planning to do more refactoring on this plugin soon. I improved a few things in the previous update, however some parts of the plugin are still really not that great. There are still parts left over from it's first release in April of 2017 actually.

I hope this answers your questions!
